# Spring Specification
springSpecification:
  datasource:
    url: jdbc:h2:mem:testdb
    data: spring-specification/data.sql
  jpa:
    show-sql: true

# Sample application
spring:
  datasource:
    url: jdbc:hsqldb:mem:testdb
