# https://travis-ci.org/pinguet62/spring-specification

language: java
jdk: oraclejdk8

before_install:
    # Karma: http://karma-runner.github.io/0.8/plus/Travis-CI.html
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install: true # override default "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"

script: # override default "mvn test -B"
    - mvn clean install -B

after_success:
    # Code coverage: report
    - bash <(curl -s https://codecov.io/bash) # CodeCov

    # Deploy: SNAPSHOT + AsciiDoc (to GitHub pages) + preview (to Heroku)
    - test $TRAVIS_BRANCH = "master" &&
      test $TRAVIS_PULL_REQUEST = "false" &&
      mvn deploy -DskipTests --settings deploy-settings.xml
