# https://travis-ci.org/pinguet62/spring-specification

language: java
jdk: oraclejdk8

after_success:
    # Code coverage
    # * https://coveralls.io/github/pinguet62/spring-specification
    - mvn jacoco:report coveralls:report
    # * https://codecov.io/gh/pinguet62/spring-specification
    - bash <(curl -s https://codecov.io/bash)
    
    # Deploy SNAPSHOT & doc
    - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" &&
      mvn deploy -DskipTests --settings deploy-settings.xml"
