# https://travis-ci.org/pinguet62/spring-specification

language: java
jdk: oraclejdk8

before_install:
    # Karma: http://karma-runner.github.io/0.8/plus/Travis-CI.html
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

after_success:
    # Code coverage: report (CodeCov)
    - bash <(curl -s https://codecov.io/bash)
    
    # Deploy SNAPSHOT & doc
    - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" &&
      mvn deploy -DskipTests --settings deploy-settings.xml
